name: Lint and Test

on: pull_request

jobs:

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  tests:
    runs-on: ubuntu-latest
    needs: static-checks
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Run tests
        # Directory creation step required for testing
        run: |
          mkdir -p ~/.ssh
          chmod -R 666 ~/.ssh
          just build
          just up
          just test
