name: Lint and Test

on: pull_request

jobs:

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  tests:
    runs-on: ubuntu-latest
    needs: static-checks
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Run tests
        # Directory creation step required for testing
        env:
          SSH_DIRECTORY: /tmp/ssh
        run: |
          set -x
          mkdir -p $SSH_DIRECTORY/.ssh
          chmod -R 777 $SSH_DIRECTORY
          ls -lah $SSH_DIRECTORY/.ssh
          just build
          just up
          just _dc config
          just test
